---
title: "Palmer Penguins Dashboard"
author: "Sano Tanna"
format: dashboard
---

```{r, echo=FALSE}
library(tidyverse)
library(plotly)
library(janitor)

penguins <- read.csv("data/penguins_lter copy.csv")

penguins <- penguins %>%
  clean_names()
```

Instructions: Make a Dashboard with two rows. Row 1 should contain two graphs showing any penguin data that you'd like. Row 2 should contain a table (use knitr::kable and select if you'd like to narrow down the columns). Then customize your dashboard by adding colors, labels, interactivity,etc.

Optional: Add text cards, value boxes, tabs, pages, etc.

```{r}

library(ggplot2)
library(plotly)
library(palmerpenguins)

# Create ggplot first
p <- ggplot(penguins, aes(flipper_length_mm, body_mass_g, color = species)) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Palmer Penguins: Flipper Length vs Body Mass",
    x = "Flipper length (mm)",
    y = "Body mass (g)"
  )

# Convert ggplot to interactive Plotly plot
ggplotly(p)
```

```{r}
penguins <- penguins %>%
  select(-comments)
knitr::kable(penguins)
```

```{r}
```
